package com.ozcanorhandemirci.hava.core.database

import com.ozcanorhandemirci.hava.core.database.entity.CityEntity

/**
 * The places the application knows on first launch.
 *
 * Chosen for range rather than for size alone. Rize and Trabzon are among the
 * wettest places in the country, Erzurum and Ardahan among the coldest, Antalya
 * and Adana among the hottest, and Van and Konya sit inland where the sky
 * behaves differently again. Opening the list should show weather that actually
 * differs from one row to the next.
 *
 * Each identifier is the one the geocoding service issues for that place, so a
 * city reached through search resolves to the same row rather than a duplicate.
 */
internal val SeedCities = listOf(
    CityEntity(
        id = 745044L,
        name = "İstanbul",
        region = "İstanbul",
        countryCode = "TR",
        latitude = 41.0138,
        longitude = 28.9497,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 323786L,
        name = "Ankara",
        region = "Ankara",
        countryCode = "TR",
        latitude = 39.9199,
        longitude = 32.8543,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 311046L,
        name = "İzmir",
        region = "İzmir",
        countryCode = "TR",
        latitude = 38.4127,
        longitude = 27.1384,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 323777L,
        name = "Antalya",
        region = "Antalya",
        countryCode = "TR",
        latitude = 36.9081,
        longitude = 30.6956,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 750269L,
        name = "Bursa",
        region = "Bursa İli",
        countryCode = "TR",
        latitude = 40.1956,
        longitude = 29.0601,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 325363L,
        name = "Adana",
        region = "Adana",
        countryCode = "TR",
        latitude = 36.9862,
        longitude = 35.3253,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 738648L,
        name = "Trabzon",
        region = "Trabzon",
        countryCode = "TR",
        latitude = 41.005,
        longitude = 39.7269,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 740483L,
        name = "Rize",
        region = "Rize",
        countryCode = "TR",
        latitude = 41.0208,
        longitude = 40.5219,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 315368L,
        name = "Erzurum",
        region = "Erzurum",
        countryCode = "TR",
        latitude = 39.9086,
        longitude = 41.2769,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 298117L,
        name = "Van",
        region = "Van",
        countryCode = "TR",
        latitude = 38.4946,
        longitude = 43.3832,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 314830L,
        name = "Gaziantep",
        region = "Gaziantep",
        countryCode = "TR",
        latitude = 37.0594,
        longitude = 37.3825,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 306571L,
        name = "Konya",
        region = "Konya",
        countryCode = "TR",
        latitude = 37.8713,
        longitude = 32.4846,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 308464L,
        name = "Kayseri",
        region = "Kayseri",
        countryCode = "TR",
        latitude = 38.7322,
        longitude = 35.4853,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 740264L,
        name = "Samsun",
        region = "Samsun İli",
        countryCode = "TR",
        latitude = 41.2798,
        longitude = 36.3361,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 316541L,
        name = "Diyarbakır",
        region = "Diyarbakır",
        countryCode = "TR",
        latitude = 37.9136,
        longitude = 40.2172,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 304184L,
        name = "Muğla",
        region = "Muğla",
        countryCode = "TR",
        latitude = 37.2181,
        longitude = 28.3665,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 315202L,
        name = "Eskişehir",
        region = "Eskişehir",
        countryCode = "TR",
        latitude = 39.7767,
        longitude = 30.5206,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 304922L,
        name = "Malatya",
        region = "Malatya",
        countryCode = "TR",
        latitude = 38.3502,
        longitude = 38.3167,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 749780L,
        name = "Çanakkale",
        region = "Çanakkale",
        countryCode = "TR",
        latitude = 40.1555,
        longitude = 26.4127,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
    CityEntity(
        id = 751952L,
        name = "Ardahan",
        region = "Ardahan",
        countryCode = "TR",
        latitude = 41.1087,
        longitude = 42.7022,
        timeZoneId = "Europe/Istanbul",
        favoritedAt = null,
    ),
)
